# Generated by Django 6.0.6 on 2026-06-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='characteristics',
            field=models.ManyToManyField(to='api.characteristic'),
        ),
    ]
